### ISSUE TITLE
Suggestion: add requirements.txt

### ISSUE THREAD

**Issue by sgbaird** [TRI-AMDD/piro#59]
Not essential, but might help people to get up and running sooner if there's a dependency issue so they can install a known set of compatible dependencies via `pip install -r requirements.txt` as a last resort.

**Comment by sgbaird** [comment]
E.g. via:
```
pip install pipreqs
pipreqs .
```
Then manually pin the versions. Also, I'm now noticing your CI workflows and seeing if I can figure out my issue in #57.

**Comment by JosephMontoya-TRI** [comment]
Agreed, not sure why we hadn't done this until now - just added.  Dependabot should update from now on as well.  Thanks!
