### ISSUE TITLE
Approximately how long should the example notebooks take to run? (specifically `BaTiO3-Example.ipynb`)

### ISSUE THREAD

**Issue by sgbaird** [TRI-AMDD/piro#60]

**Comment by JosephMontoya-TRI** [comment]
Just tested, looks like around 5-10 minutes on my machine.  Note that it should be faster the second time around, since piro caches the intermediate structure matching results.

**Comment by JosephMontoya-TRI** [comment]
I've added a note in the BaTiO3 note on the timing, just for future reference.
